# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PubNubSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PubNubSample

  pod 'PubNubSwift', '~> 3.0.1'

  target 'PubNubSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PubNubSampleUITests' do
    # Pods for testing
  end

end
